name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build Magisk Module
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Compile
      run: ./compile.sh
    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: MagicalProtection.zip
        path: |
          MagicalProtection-*.zip
        if-no-files-found: error
